//! Acceptance test for AC3 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: fsstory (cli)
//! AC description: When no ctrace log is available (graceful degradation), `fsstory path <path>` still emits an event list derived from stat mtime + path heuristics, with `confidence: low`, and exits 0. It never errors solely because ctrace was off.
//! Test predicate: tests/acceptance_ac3.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac3` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac3() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC3 not yet implemented — see file header");
}
