//! Acceptance test for AC8 (MAY) — generated by `autobuilder scaffold`.
//!
//! Project: fsstory (cli)
//! AC description: The CLI's `--format json` output for `fsstory path` and `fsstory ls` is stable enough across runs that two consecutive invocations on the same fixture produce identical byte-streams.
//! Test predicate: tests/acceptance_ac8.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac8` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

use std::io::Write;
use std::process::Command;
use tempfile::tempdir;

#[test]
fn acceptance_ac8() {
    let bin = env!("CARGO_BIN_EXE_fsstory");
    let cdir = tempdir().unwrap();
    let jdir = tempdir().unwrap();
    let nd = cdir.path().join("a.ndjson");
    let mut f = std::fs::File::create(&nd).unwrap();
    writeln!(
        f,
        r#"{{"ts":100,"syscall":"openat","flags":"WRONLY","file":"/tmp/stable","pid":1,"comm":"claude"}}"#
    )
    .unwrap();
    writeln!(
        f,
        r#"{{"ts":200,"syscall":"openat","flags":"WRONLY","file":"/tmp/stable","pid":2,"comm":"nvim"}}"#
    )
    .unwrap();
    let run = || -> Vec<u8> {
        let out = Command::new(bin)
            .arg("--ctrace-root")
            .arg(cdir.path())
            .arg("--claude-root")
            .arg(jdir.path())
            .arg("path")
            .arg("/tmp/stable")
            .arg("--since")
            .arg("999999999s") // include all ts back to epoch
            .arg("--format")
            .arg("json")
            .output()
            .unwrap();
        assert!(out.status.success());
        out.stdout
    };
    let a = run();
    let b = run();
    assert_eq!(a, b, "JSON output not byte-identical across runs");
}
