//! Acceptance test for AC4 (MUST) — generated by `autobuilder scaffold`.
//!
//! Project: fsstory (cli)
//! AC description: `fsstory who-wrote <path>` exits 0 and emits exactly one line: the latest attributed event for `<path>` formatted as `<ts>\t<actor>\t<confidence>`.
//! Test predicate: tests/acceptance_ac4.rs
//!
//! Ownership split: this //! header block (AC metadata) is
//! read-only — to change an AC, file
//! agent/intent_card_amendment_request.json and re-scaffold. The
//! `fn acceptance_ac4` body BELOW is owned by the edit-agent: replace
//! the panic stub with a real assertion that verifies the AC
//! description above.

#![allow(clippy::unwrap_used, clippy::expect_used, clippy::doc_markdown)]

#[test]
fn acceptance_ac4() {
    // edit-agent: replace this stub with a real assertion. The
    // panic keeps the test failing until you do, so the loop
    // sees a real Stage 3 signal.
    panic!("AC AC4 not yet implemented — see file header");
}
